[[pages]]
path = "/"
screenshotTimestamp = "2026-05-03T18:52:07Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/ef16b221-d9db-4c04-a9d7-fb3613038e82/6f875328-a889-4bfe-a3a4-f1e6ba0fb0ae/f886Xdr"

[[pages]]
path = "/product/coco-gut"
screenshotTimestamp = "2026-05-03T18:05:40Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/ef16b221-d9db-4c04-a9d7-fb3613038e82/6f875328-a889-4bfe-a3a4-f1e6ba0fb0ae/3OYgfiw"
